- name: Configure Docker
  hosts: all
  tasks:
  - name: "Creating Directory"
    file:
      state: directory
      path: "/dvd"

  - name: "Mounting Directory"
    mount:
      src: "/dev/cdrom"
      path: "/dvd"
      state: mounted
      fstype: "iso9660"

  - name: "DVD1"
    yum_repository:
      name: "dvd1"
      baseurl: "/dvd/AppStream"
      description: "AppStream"
      gpgcheck: no

  - name: "DVD2"
    yum_repository:
      name: "dvd2"
      baseurl: "/dvd/BaseOS"
      description: "BaseOS"
      gpgcheck: no

  - name: "Docker Repo Creation"
    yum_repository:
      name: "docker"
      description: "docker repo"
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
      gpgcheck: no

  - name: "Docker Installation"
    package:
      name: "docker-ce-18.09.1-3.el7.x86_64"
      state: present
      enablerepo: "docker"

  - name: "Starting Docker Service"
    service:
      name: "docker"
      state: started
      enabled: yes

  - name: "Pip3 Installation"
    package:
      name: "python36-3.6.8-1.module+el8+2710+846623d6.x86_64"
      state: present

  - name: "Installation of  Docker SDK"
    command: "pip3 install docker"

  - name: "Creating folder"
    file:
      path: "/mytask"
      state: directory

  - name: "Copying HTML File"
    copy:
      content: "This file is created in a Docker Container automated by Ansible"
      dest: "/mytask/index.html"

  - name: "Creating Container using HTTPD Image"
    docker_container:
      name: "WebServer"
      image: "httpd"
      state: started
      exposed_ports: "80"
      ports: "8080:80"
      volumes: /mytask:/usr/local/apache2/htdocs/

  - name: Stopping the firewall to allow outside world to view webpage
    service:
       name: firewalld
       state: stopped
